############Users#####################
##Add user
POST http://localhost:6900/users/
Content-Type: application/json

{
    "firstName": "dgdgdg",
    "lastName": "gdgdgdh",
    "email": "motapax198@farebus.com",
	"password": "Amazing@2023",
    "address": "798 Central Perk"
}


### Login User
GET http://localhost:6900/users/login
Content-Type: application/json

{
  "email": "motapax198@farebus.com",
	"password": "Amazing@2023"
}


### Get all users
GET  http://localhost:6900/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1NjQ5YzJlLWE0YmYtNGQyYi1iNTU0LWRjYmVlODEwYTU2ZSIsImVtYWlsIjoiY2hhbmRsZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiZW1haWxTZW50Ijp0cnVlLCJhcHByb3ZlZCI6dHJ1ZSwiaWF0IjoxNjg0NjgxNzkwLCJleHAiOjE2ODQ2ODUzOTB9.CZLup6VkaExgtGIJwdWtnxLNPNL__H-36w_0XsDmQww



### Get user by ID
GET  http://localhost:6900/users/user?id=b36d4551-b91a-4e72-ae89-b308deb618c4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1NjQ5YzJlLWE0YmYtNGQyYi1iNTU0LWRjYmVlODEwYTU2ZSIsImVtYWlsIjoiY2hhbmRsZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYXBwcm92ZWQiOmZhbHNlLCJpYXQiOjE2ODQ0MzkwNDYsImV4cCI6MTY4NDQ0MjY0Nn0.RaKod1C_yAsMRYT_hUZgdKb_BTQlxY3BbL2LFqfM2cg

### Get user by email
GET  http://localhost:6900/users/mail?email=chandler@gmail.com
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1NjQ5YzJlLWE0YmYtNGQyYi1iNTU0LWRjYmVlODEwYTU2ZSIsImVtYWlsIjoiY2hhbmRsZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYXBwcm92ZWQiOmZhbHNlLCJpYXQiOjE2ODQ0MzkwNDYsImV4cCI6MTY4NDQ0MjY0Nn0.RaKod1C_yAsMRYT_hUZgdKb_BTQlxY3BbL2LFqfM2cg 


### Password reset
POST http://localhost:6900/users/b36d4551-b91a-4e72-ae89-b308deb618c4
Content-Type: application/json

{
    "email": "motapax198@farebus.com"
}

### Update user
PUT http://localhost:6900/users/0355ba85-162c-42f3-9bdd-758237ffb0db
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIzNmQ0NTUxLWI5MWEtNGU3Mi1hZTg5LWIzMDhkZWI2MThjNCIsImVtYWlsIjoibW9uaWNhQGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImVtYWlsU2VudCI6ZmFsc2UsImFwcHJvdmVkIjpmYWxzZSwiaWF0IjoxNjg0Njg0NTk1LCJleHAiOjE2ODQ2ODgxOTV9.avn1gQ5wW7tF1Nh2F8x9aSBV6Yq_JSqwZyENKeQ8B_o

{
	"firstName": "Monica",
    "lastName": "Geller",
    "email": "siwid70008@andorem.com",
	"password": "chanandlerbong",
    "address": "254 Museum Road"
}

### Delete user
DELETE  http://localhost:6900/users/f27cf748-4e2a-429b-b198-b4d493003e6e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1NjQ5YzJlLWE0YmYtNGQyYi1iNTU0LWRjYmVlODEwYTU2ZSIsImVtYWlsIjoiY2hhbmRsZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYXBwcm92ZWQiOmZhbHNlLCJpYXQiOjE2ODQ0NDMyMzQsImV4cCI6MTY4NDQ0NjgzNH0.MJRXIaVBL9KdPQxnGHmJ-JoGY0qPAsgpUzzLxtPqrZg

############Products##################
### Create product
POST http://localhost:6900/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1NjQ5YzJlLWE0YmYtNGQyYi1iNTU0LWRjYmVlODEwYTU2ZSIsImVtYWlsIjoiY2hhbmRsZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiZW1haWxTZW50Ijp0cnVlLCJhcHByb3ZlZCI6dHJ1ZSwiaWF0IjoxNjg0NTk0MjM2LCJleHAiOjE2ODQ1OTc4MzZ9.BEPU2dCA4UWPGv-3PWCjWjM0YD4yfWwbiU6pU_V1xZw

{
    "productName": "Sony Alpha a7 V",
    "description": "Professional mirrorless camera",
    "longDescription": "The Sony Alpha a7 III offers high-resolution imaging, advanced autofocus, and 4K video recording capabilities, making it a top choice for professional photographers.",
    "unitPrice":5450,
    "discount": 29.99,
    "category": "Digital Cameras",
    "stock": 24
}


### Get all products
GET http://localhost:6900/products/



### Get product by ID
GET http://localhost:6900/products/product?id=f3219f85-773e-474b-a064-7edc9e84f20c


### Get product by name
GET http://localhost:6900/products/name?productName=Sony

### Get product by price range
GET http://localhost:6900/products/range
Content-Type: application/json

{
	"minPrice": 4190,
	"maxPrice": 5000
}

### Get products by quantity range
GET http://localhost:6900/products/stock
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1NjQ5YzJlLWE0YmYtNGQyYi1iNTU0LWRjYmVlODEwYTU2ZSIsImVtYWlsIjoiY2hhbmRsZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYXBwcm92ZWQiOnRydWUsImlhdCI6MTY4NDQ0NzQ3MywiZXhwIjoxNjg0NDUxMDczfQ.9ieBhtN_OGpqN__hdg1lQOO4feshnDD77zPUlBTUqW4


{
	"minQuantity": 20,
	"maxQuantity": 30
}

### Get product by availability
GET http://localhost:6900/products/iko
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1NjQ5YzJlLWE0YmYtNGQyYi1iNTU0LWRjYmVlODEwYTU2ZSIsImVtYWlsIjoiY2hhbmRsZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYXBwcm92ZWQiOnRydWUsImlhdCI6MTY4NDQ0NzQ3MywiZXhwIjoxNjg0NDUxMDczfQ.9ieBhtN_OGpqN__hdg1lQOO4feshnDD77zPUlBTUqW4

### Update product
PUT http://localhost:6900/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1NjQ5YzJlLWE0YmYtNGQyYi1iNTU0LWRjYmVlODEwYTU2ZSIsImVtYWlsIjoiY2hhbmRsZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiYXBwcm92ZWQiOnRydWUsImlhdCI6MTY4NDQ0NzQ3MywiZXhwIjoxNjg0NDUxMDczfQ.9ieBhtN_OGpqN__hdg1lQOO4feshnDD77zPUlBTUqW4

{
	 "id": "09ad589b-9ea4-4227-bcc6-c02e5dc284c4",
    "productName": "Sony Alpha a7 Iv",
    "description": "Professional mirrorless camera",
    "longDescription": "The Sony Alpha a7 III offers high-resolution imaging, advanced autofocus, and 4K video recording capabilities, making it a top choice for professional photographers.",
    "unitPrice": 4250,
    "discount": 69.99,
    "category": "Digital Cameras",
    "stock": 24
}


### Delete product
DELETE http://localhost:6900/products/d0a06f2c-b112-4544-8668-8924024d5124
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImY1NjQ5YzJlLWE0YmYtNGQyYi1iNTU0LWRjYmVlODEwYTU2ZSIsImVtYWlsIjoiY2hhbmRsZXJAZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiZW1haWxTZW50Ijp0cnVlLCJhcHByb3ZlZCI6dHJ1ZSwiaWF0IjoxNjg0NTkwNzcxLCJleHAiOjE2ODQ1OTQzNzF9.xvHseya2Ha4Qm3UM3ARqv-okJvtdBQRTwrEMt0eXoxM

############Cart#####################
### Add to Cart
POST http://localhost:6900/cart/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxYjY2ZjE5LTgxMTYtNDczNC1iNDVjLTkzYjc2MWZjM2MzZiIsImVtYWlsIjoicm9zc0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJhcHByb3ZlZCI6ZmFsc2UsImlhdCI6MTY4NDQ3NTQxNCwiZXhwIjoxNjg0NDc5MDE0fQ.j0w1z13uSzh1RQuF-ozNblZfnFM__V98F2FioqaLA3M

{
    "productID": "70a919e9-54bf-41ad-9b48-145484546a35",
    "quantity": 3,
    "unitPrice": 2499,
    "discount": 99
}

### Get Cart Items
GET http://localhost:6900/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxYjY2ZjE5LTgxMTYtNDczNC1iNDVjLTkzYjc2MWZjM2MzZiIsImVtYWlsIjoicm9zc0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJhcHByb3ZlZCI6ZmFsc2UsImlhdCI6MTY4NDQ3NTQxNCwiZXhwIjoxNjg0NDc5MDE0fQ.j0w1z13uSzh1RQuF-ozNblZfnFM__V98F2FioqaLA3M


### Remove from Cart
DELETE http://localhost:6900/cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxYjY2ZjE5LTgxMTYtNDczNC1iNDVjLTkzYjc2MWZjM2MzZiIsImVtYWlsIjoicm9zc0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJhcHByb3ZlZCI6ZmFsc2UsImlhdCI6MTY4NDQ0OTg3OSwiZXhwIjoxNjg0NDUzNDc5fQ.5K_guN9Kcq9IKZFl1KTjHylwKxSN0NyMkfPuRn0NSK0


{
    "itemID": "b910d84c-4a5a-4526-8498-c05eb0a37e83"
}

### Clear cart
DELETE http://localhost:6900/cart/clear
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjQxYjY2ZjE5LTgxMTYtNDczNC1iNDVjLTkzYjc2MWZjM2MzZiIsImVtYWlsIjoicm9zc0BnbWFpbC5jb20iLCJyb2xlIjoiY3VzdG9tZXIiLCJhcHByb3ZlZCI6ZmFsc2UsImlhdCI6MTY4NDQ3NTQxNCwiZXhwIjoxNjg0NDc5MDE0fQ.j0w1z13uSzh1RQuF-ozNblZfnFM__V98F2FioqaLA3M


###############Orders################
