############Users#####################
##Add user
POST http://localhost:6900/users/
Content-Type: application/json

{
  	"username": "chandler",
	"password": "chanandlerbong",
    "email": "chandler@gmail.com",
    "first_name": "Chandler",
    "last_name": "Bing",
    "address": "789 Central Perk Lane",
    "city": "New York"
}

### Get all users
GET  http://localhost:6900/users/


### Get user by ID
GET  http://localhost:6900/users/user?UserID=9a48d3f3-43ee-468d-bf5c-e991a9eb2749

### Get user by email
GET  http://localhost:6900/users/mail?email=chandler@gmail.com

### Update user
PUT http://localhost:6900/users/1096c55b-ff29-4575-a6da-15ff1cfacdc2
Content-Type: application/json

{
	"username": "monicageller",
	"password": "chanandlerbong",
    "email": "monica@gmail.com",
    "first_name": "Monica",
    "last_name": "Geller",
    "address": "789 Central Perk Lane",
    "city": "New York"
}

### Delete user
DELETE  http://localhost:6900/users/f152e539-029d-4d2c-9086-4505c2bb8372

############Products##################
### Create product
POST http://localhost:6900/products/
Content-Type: application/json

{
	"productName": "Product 6",
    "description": "This is product 6",
    "longDescription": "A long description for product 6",
    "price": "6000",
    "category": "Category 1",
    "stock": 60,
    "images":"https://example.com/product6.jpg"
}

### Get all products
GET http://localhost:6900/products/



### Get product by ID
GET http://localhost:6900/products/product?id=2e1d733e-7865-4bb6-ace9-293cff8dafb9


### Get product by name
GET http://localhost:6900/products/name?productName=Product 5

### Get product by price range
GET http://localhost:6900/products/range
Content-Type: application/json

{
	"minPrice": 2000,
	"maxPrice": 4000
}


### Get products by quantity range
GET http://localhost:6900/products/stock
Content-Type: application/json


{
	"minQuantity": 20,
	"maxQuantity": 30
}

### Get product by availability
GET http://localhost:6900/products/iko

### Update product
PUT http://localhost:6900/products/
Content-Type: application/json

{
	"productID": "7fd3b2ab-5cb4-4825-8aaf-08dc5a4ba235",
	"productName": "Product 6",
    "description": "This is product 6",
    "longDescription": "A long description for product 6",
    "category": "Category 1",
    "price": "6900",
    "stock": 69,
    "images":"https://example.com/product6.jpg"
}


### Delete product
DELETE http://localhost:6900/products/7fd3b2ab-5cb4-4825-8aaf-08dc5a4ba235
Content-Type: application/json