CREATE TABLE Cart
(
    CartID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CustomerID VARCHAR(50) NOT NULL,
    CreatedDate DATETIME NOT NULL,
    CONSTRAINT FK_Cart_Users FOREIGN KEY (CustomerID) REFERENCES Users (UserID)
);
