CREATE TABLE CartItems
(
    CartItemID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    CartID INT NOT NULL,
    ProductID VARCHAR(50) NOT NULL,
    Quantity INT NOT NULL,
    UnitPrice DECIMAL(10, 2) NOT NULL,
    TotalPrice DECIMAL(10, 2) NOT NULL,
    CONSTRAINT FK_CartItems_Cart FOREIGN KEY (CartID) REFERENCES Cart (CartID),
    CONSTRAINT FK_CartItems_Products FOREIGN KEY (ProductID) REFERENCES Products (ProductID)
);
